version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sql-parse"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19btuesgs89pz"
s3_prefix = "sql-parse"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"production\""
image_repositories = []
